### ISSUE TITLE
tests/test_simple_env_agents.py doesn't provide bet amounts

### ISSUE THREAD

**Issue by blumx116** [blumx116/VotingIsAllYouNeed#14]
a required 'bet' parameter will be added to specs for Agent Factory.
The tests need to be updated to provide this parameter.

**Comment by blumx116** [comment]
Right now, an ActionBet is passed in, which does technically contain all of the information needed, but this doesn't extend well for other situations. For instance, in the case where the agent is random, right now the prediction would be unspecified but we would still want to specify the bet amount. 

Additionally, I think it's a little bit of an abuse of the type, as it is just being used as a struct and not a literal bet.

**Comment by alnah005** [comment]
I agree with not using ActionBet as a struct. I'll update the tests.

For random, I thought it would just assign a random probability based on the seed?

**Comment by blumx116** [comment]
In the LaTeX specs, we said that all of the agents were going to submit static bets of 0.5 for the first few experiments.

**Comment by alnah005** [comment]
In the future, shouldn't random submit a random bet?

**Comment by blumx116** [comment]
I think we should do a few tests like that, but I think that the static bet is easiest for analysis. We can just add it as a factory option when the time comes, I think.
