### ISSUE TITLE
Agents use WeightedBet instead of ActionBet

### ISSUE THREAD

**Issue by alnah005** [blumx116/VotingIsAllYouNeed#27]
`WeightedBet` is used everywhere except in `bet` of the agent. Also, `WeightedBet` has all the attributes that `ActionBet` has. I think having both might be redundant so if we make agents generate `WeightedBet` in `bet`, we could delete AgentBet. We also need to refactor the tests to reflect this change.

**Comment by blumx116** [comment]
We want to restrict the ways that the bets can be used & generated (e.g. payouts should be invariant to who cast the bet), so in some places I think we want to restrict people to only seeing the information in ActionBet.

That being said, I think that it's good idea to make WeightedBet inherit from ActionBet, I'll implement.
