### ISSUE TITLE
Make Simple Agents That Don't Ignore State

### ISSUE THREAD

**Issue by blumx116** [blumx116/VotingIsAllYouNeed#38]
For each of vote, bet & prediction, add in the following configuration options:
  - random range by state
  - constant value by state

Currently supported state is IntAction

**Comment by blumx116** [comment]
Add a dict_to_fn function to utils to easily create lookups 

```
def dict_to_fn(dict: Dict[T, V]) -> Callable[[T], V]:
      ....
```

**Comment by blumx116** [comment]
Add prediction_fn, voting_fn and bet_fn to agent spec. Add functional agent to the factory spec enum.

**Comment by alnah005** [comment]
```
class bet(object):
    def __init__(self,N, constant):
           assert 0 < constant <= 1
           self.N = N
           self.constant = constant
    def __call__(self) -> List[float]:
           res = np.random(N) # vector of size N
           return list(res*constant/sum(res))

class Prediction(object):
    def __init__(self, N, VoteBounds):
           assert 0 < constant <= 1
           self.N = N
           self.VoteBounds = VoteBounds
    def __call__(self) -> List[float]:
           res = np.random(N, low = VoteBounds.min, high =VoteBounds.max) # vector of size N
           return list(res)

class Vote(object):
    def __init__(self,N, voteRange):
           assert 0 < constant <= 1
           self.N = N
           self.voteRange = voteRange
    def __call__(self) -> float:
           return np.random(low = voteRange.min, high = voteRange.max)
```

Instead of having the type of vote, prediction, and bet be callable functions, do we want to do something like this?

**Comment by blumx116** [comment]
These seem really similar to the `BetSelectionMechanism`, `PredictionSelectionMechanism` and `VotingMechanism` currently in agents.py. 

I like the idea of having them passed in instead of the raw functions, because it makes things clearer. Let's do it.
