### ISSUE TITLE
Create Experiment Structure

### ISSUE THREAD

**Issue by blumx116** [blumx116/VotingIsAllYouNeed#4]
Need to create agents & environment to be passed in to train() for experiment 1.
One agent should be configured to give out a constant prediction.
The other agent should give random predictions (seed should be easily set).
Both agents should give out a constant vote.
The environment can completely be a dummy.

**Comment by blumx116** [comment]
Depends on #7

**Comment by alnah005** [comment]
Should we create an agent factory?

**Comment by blumx116** [comment]
I'm a fan. Let's do it.

**Comment by alnah005** [comment]
```
return AgentFactory._creators_[spec.agentType](spec)
E       TypeError: 'staticmethod' object is not callable
```
But adding this: 
```
AgentsEnum.random: lambda x: AgentFactory._create_random_agent_(x),
AgentsEnum.constant: lambda x: AgentFactory._create_static_agent_(x)
```
Fixes it. Let me know if you have a better solution.
