### ISSUE TITLE
Create new payouts with max replaced by 95th percentile

### ISSUE THREAD

**Issue by blumx116** [blumx116/VotingIsAllYouNeed#40]
Only need to create a new version corresponding to the current 'suggested' model, although we could create a new one for 'simple' as well if it works well in the interface.

**Comment by blumx116** [comment]
Should add an additional optional enum argument to the payout spec, like follows:

```
@unique
class PayoutUpperBoundEnum(Enum):
    max = auto()
    quartile95 = auto()


@dataclass(frozen=True)
class PayoutConfigFactorySpec:
    configType: PayoutConfigEnum
    upper_bound: PayoutUpperBoundEnum = PayoutUpperBoundEnum.max

    def __post_init__(self):
        pass

```

This maintains backwards compatibility and helps lessen the cognitive load of users.

**Comment by alnah005** [comment]
based on overleaf,  ![equation](https://bit.ly/3p2TJDI)  which means agents will always get less than or equal to their bet amounts not more.

**Comment by alnah005** [comment]
Perhaps we can have this? ![equation](https://bit.ly/3mBZW7R) where mean_i^g is the mean of the 95% confidence bets

**Comment by blumx116** [comment]
Updating the Latex to show this - > doesn't have (0, 1) issue

![image](https://user-images.githubusercontent.com/15827967/102813605-bb328780-438e-11eb-9272-91f578d79fe1.png)
