### ISSUE TITLE
Propagate Weighted through project

### ISSUE THREAD

**Issue by blumx116** [blumx116/VotingIsAllYouNeed#53]
Weighted is a new type to replace the many, many instances of Tuple[float, float] throughout the system, where the first value is assumed to be a weight. It should add clarity & safety to the code, as it checks that the weight is nonzero upon construction.

**Comment by alnah005** [comment]
We should look into making weighted a tuple. Something similar to this:
```
class Point(tuple):
    def __init__(self,size):
        print("hello")
        self.size = size
    def __setattr__(self, name, value):
        if name == "size":
            raise AttributeError("size is immutable")
        self.__dict__[name] = value
    def __new__(cls,size):
        return super().__new__(cls, (0,) * size)

p = Point(5)
p2 = Point(3)
print(p)
print(p2)
print(p.size)
p.size = 20
print(p)
```
here are some resources on `__new__`:
 - https://github.com/google/pytype/issues/500
 - https://bugs.python.org/issue34362
