### ISSUE TITLE
Tests: PolicyConfiguration

### ISSUE THREAD

**Issue by blumx116** [blumx116/VotingIsAllYouNeed#6]
# Argmax
 - Single vote for each 
 - Different Money
 - Different Bets
 - Different Bets & Money
 - No votes for some action
 - No votes for any action
# Thompson Sampling
  - All of above
  - Monte Carlo samples to see if we approach the correct distribution

**Comment by alnah005** [comment]
# Argmax
 - [x] Single vote for each 
 - [x] Different Money
 - [x] Different Bets
 - [x] Different Bets & Money
 - [x] No votes for some action
 - [x] No votes for any action
# Thompson Sampling
  - [ ] All of above
  - [ ] Monte Carlo samples to see if we approach the correct distribution

**Comment by alnah005** [comment]
# Argmax
 - [x] Single vote for each 
 - [x] Different Money
 - [x] Different Bets
 - [x] Different Bets & Money
 - [x] No votes for some action
 - [x] No votes for any action
# Thompson Sampling
  - [x] All of above
  - [x] Monte Carlo samples to see if we approach the correct distribution
         created classes that simulate going to the correct distribution.
